name: pipeline

on: push

env:
  TARGETARCH: amd64

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ github.repository_owner }}
        run: make image push TARGETARCH=$TARGETARCH
      - name: Clean
        run: make clean TARGETARCH=$TARGETARCH
